/*
 * Copyright (c) 2026 MediaTek Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MTK_MT8188_CLOCK_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MTK_MT8188_CLOCK_H_

/* TOPCKGEN */
#define CLK_TOP_AXI                       0
#define CLK_TOP_SPM                       1
#define CLK_TOP_SCP                       2
#define CLK_TOP_BUS_AXIMEM                3
#define CLK_TOP_VPP                       4
#define CLK_TOP_ETHDR                     5
#define CLK_TOP_IPE                       6
#define CLK_TOP_CAM                       7
#define CLK_TOP_CCU                       8
#define CLK_TOP_CCU_AHB                   9
#define CLK_TOP_IMG                       10
#define CLK_TOP_CAMTM                     11
#define CLK_TOP_DSP                       12
#define CLK_TOP_DSP1                      13
#define CLK_TOP_DSP2                      14
#define CLK_TOP_DSP3                      15
#define CLK_TOP_DSP4                      16
#define CLK_TOP_DSP5                      17
#define CLK_TOP_DSP6                      18
#define CLK_TOP_DSP7                      19
#define CLK_TOP_MFG_CORE_TMP              20
#define CLK_TOP_CAMTG                     21
#define CLK_TOP_CAMTG2                    22
#define CLK_TOP_CAMTG3                    23
#define CLK_TOP_UART                      24
#define CLK_TOP_SPI                       25
#define CLK_TOP_MSDC50_0_HCLK             26
#define CLK_TOP_MSDC50_0                  27
#define CLK_TOP_MSDC30_1                  28
#define CLK_TOP_MSDC30_2                  29
#define CLK_TOP_INTDIR                    30
#define CLK_TOP_AUD_INTBUS                31
#define CLK_TOP_AUDIO_H                   32
#define CLK_TOP_PWRAP_ULPOSC              33
#define CLK_TOP_ATB                       34
#define CLK_TOP_SSPM                      35
#define CLK_TOP_DP                        36
#define CLK_TOP_EDP                       37
#define CLK_TOP_DPI                       38
#define CLK_TOP_DISP_PWM0                 39
#define CLK_TOP_DISP_PWM1                 40
#define CLK_TOP_USB_TOP                   41
#define CLK_TOP_SSUSB_XHCI                42
#define CLK_TOP_USB_TOP_2P                43
#define CLK_TOP_SSUSB_XHCI_2P             44
#define CLK_TOP_USB_TOP_3P                45
#define CLK_TOP_SSUSB_XHCI_3P             46
#define CLK_TOP_I2C                       47
#define CLK_TOP_SENINF                    48
#define CLK_TOP_SENINF1                   49
#define CLK_TOP_GCPU                      50
#define CLK_TOP_VENC                      51
#define CLK_TOP_VDEC                      52
#define CLK_TOP_PWM                       53
#define CLK_TOP_MCUPM                     54
#define CLK_TOP_SPMI_P_MST                55
#define CLK_TOP_SPMI_M_MST                56
#define CLK_TOP_DVFSRC                    57
#define CLK_TOP_TL                        58
#define CLK_TOP_AES_MSDCFDE               59
#define CLK_TOP_DSI_OCC                   60
#define CLK_TOP_WPE_VPP                   61
#define CLK_TOP_HDCP                      62
#define CLK_TOP_HDCP_24M                  63
#define CLK_TOP_HDMI_APB                  64
#define CLK_TOP_SNPS_ETH_250M             65
#define CLK_TOP_SNPS_ETH_62P4M_PTP        66
#define CLK_TOP_SNPS_ETH_50M_RMII         67
#define CLK_TOP_ADSP                      68
#define CLK_TOP_AUDIO_LOCAL_BUS           69
#define CLK_TOP_ASM_H                     70
#define CLK_TOP_ASM_L                     71
#define CLK_TOP_APLL1                     72
#define CLK_TOP_APLL2                     73
#define CLK_TOP_APLL3                     74
#define CLK_TOP_APLL4                     75
#define CLK_TOP_APLL5                     76
#define CLK_TOP_I2SO1                     77
#define CLK_TOP_I2SO2                     78
#define CLK_TOP_I2SI1                     79
#define CLK_TOP_I2SI2                     80
#define CLK_TOP_DPTX                      81
#define CLK_TOP_AUD_IEC                   82
#define CLK_TOP_A1SYS_HP                  83
#define CLK_TOP_A2SYS                     84
#define CLK_TOP_A3SYS                     85
#define CLK_TOP_A4SYS                     86
#define CLK_TOP_ECC                       87
#define CLK_TOP_SPINOR                    88
#define CLK_TOP_ULPOSC                    89
#define CLK_TOP_SRCK                      90
#define CLK_TOP_MFG_CK_FAST_REF           91
#define CLK_TOP_MAINPLL_D3                92
#define CLK_TOP_MAINPLL_D4                93
#define CLK_TOP_MAINPLL_D4_D2             94
#define CLK_TOP_MAINPLL_D4_D4             95
#define CLK_TOP_MAINPLL_D4_D8             96
#define CLK_TOP_MAINPLL_D5                97
#define CLK_TOP_MAINPLL_D5_D2             98
#define CLK_TOP_MAINPLL_D5_D4             99
#define CLK_TOP_MAINPLL_D5_D8             100
#define CLK_TOP_MAINPLL_D6                101
#define CLK_TOP_MAINPLL_D6_D2             102
#define CLK_TOP_MAINPLL_D6_D4             103
#define CLK_TOP_MAINPLL_D6_D8             104
#define CLK_TOP_MAINPLL_D7                105
#define CLK_TOP_MAINPLL_D7_D2             106
#define CLK_TOP_MAINPLL_D7_D4             107
#define CLK_TOP_MAINPLL_D7_D8             108
#define CLK_TOP_MAINPLL_D9                109
#define CLK_TOP_UNIVPLL_D2                110
#define CLK_TOP_UNIVPLL_D3                111
#define CLK_TOP_UNIVPLL_D4                112
#define CLK_TOP_UNIVPLL_D4_D2             113
#define CLK_TOP_UNIVPLL_D4_D4             114
#define CLK_TOP_UNIVPLL_D4_D8             115
#define CLK_TOP_UNIVPLL_D5                116
#define CLK_TOP_UNIVPLL_D5_D2             117
#define CLK_TOP_UNIVPLL_D5_D4             118
#define CLK_TOP_UNIVPLL_D5_D8             119
#define CLK_TOP_UNIVPLL_D6                120
#define CLK_TOP_UNIVPLL_D6_D2             121
#define CLK_TOP_UNIVPLL_D6_D4             122
#define CLK_TOP_UNIVPLL_D6_D8             123
#define CLK_TOP_UNIVPLL_D7                124
#define CLK_TOP_UNIVPLL_192M              125
#define CLK_TOP_UNIVPLL_192M_D4           126
#define CLK_TOP_UNIVPLL_192M_D8           127
#define CLK_TOP_UNIVPLL_192M_D10          128
#define CLK_TOP_UNIVPLL_192M_D16          129
#define CLK_TOP_UNIVPLL_192M_D32          130
#define CLK_TOP_APLL1_D3                  131
#define CLK_TOP_APLL1_D4                  132
#define CLK_TOP_APLL2_D3                  133
#define CLK_TOP_APLL2_D4                  134
#define CLK_TOP_APLL3_D4                  135
#define CLK_TOP_APLL4_D4                  136
#define CLK_TOP_APLL5_D4                  137
#define CLK_TOP_MMPLL_D4                  138
#define CLK_TOP_MMPLL_D4_D2               139
#define CLK_TOP_MMPLL_D5                  140
#define CLK_TOP_MMPLL_D5_D2               141
#define CLK_TOP_MMPLL_D5_D4               142
#define CLK_TOP_MMPLL_D6                  143
#define CLK_TOP_MMPLL_D6_D2               144
#define CLK_TOP_MMPLL_D7                  145
#define CLK_TOP_MMPLL_D9                  146
#define CLK_TOP_TVDPLL1                   147
#define CLK_TOP_TVDPLL1_D2                148
#define CLK_TOP_TVDPLL1_D4                149
#define CLK_TOP_TVDPLL1_D8                150
#define CLK_TOP_TVDPLL1_D16               151
#define CLK_TOP_TVDPLL2                   152
#define CLK_TOP_TVDPLL2_D2                153
#define CLK_TOP_TVDPLL2_D4                154
#define CLK_TOP_TVDPLL2_D8                155
#define CLK_TOP_TVDPLL2_D16               156
#define CLK_TOP_MSDCPLL_D2                157
#define CLK_TOP_MSDCPLL_D16               158
#define CLK_TOP_ETHPLL                    159
#define CLK_TOP_ETHPLL_D2                 160
#define CLK_TOP_ETHPLL_D4                 161
#define CLK_TOP_ETHPLL_D8                 162
#define CLK_TOP_ETHPLL_D10                163
#define CLK_TOP_ADSPPLL_D2                164
#define CLK_TOP_ADSPPLL_D4                165
#define CLK_TOP_ADSPPLL_D8                166
#define CLK_TOP_ULPOSC1                   167
#define CLK_TOP_ULPOSC1_D2                168
#define CLK_TOP_ULPOSC1_D4                169
#define CLK_TOP_ULPOSC1_D8                170
#define CLK_TOP_ULPOSC1_D7                171
#define CLK_TOP_ULPOSC1_D10               172
#define CLK_TOP_ULPOSC1_D16               173
#define CLK_TOP_MPHONE_SLAVE_BCK          174
#define CLK_TOP_PAD_FPC                   175
#define CLK_TOP_466M_FMEM                 176
#define CLK_TOP_PEXTP_PIPE                177
#define CLK_TOP_DSI_PHY                   178
#define CLK_TOP_APLL12_CK_DIV0            179
#define CLK_TOP_APLL12_CK_DIV1            180
#define CLK_TOP_APLL12_CK_DIV2            181
#define CLK_TOP_APLL12_CK_DIV3            182
#define CLK_TOP_APLL12_CK_DIV4            183
#define CLK_TOP_APLL12_CK_DIV9            184
#define CLK_TOP_CFGREG_CLOCK_EN_VPP0      185
#define CLK_TOP_CFGREG_CLOCK_EN_VPP1      186
#define CLK_TOP_CFGREG_CLOCK_EN_VDO0      187
#define CLK_TOP_CFGREG_CLOCK_EN_VDO1      188
#define CLK_TOP_CFGREG_CLOCK_ISP_AXI_GALS 189
#define CLK_TOP_CFGREG_F26M_VPP0          190
#define CLK_TOP_CFGREG_F26M_VPP1          191
#define CLK_TOP_CFGREG_F26M_VDO0          192
#define CLK_TOP_CFGREG_F26M_VDO1          193
#define CLK_TOP_CFGREG_AUD_F26M_AUD       194
#define CLK_TOP_CFGREG_UNIPLL_SES         195
#define CLK_TOP_CFGREG_F_PCIE_PHY_REF     196
#define CLK_TOP_SSUSB_TOP_REF             197
#define CLK_TOP_SSUSB_PHY_REF             198
#define CLK_TOP_SSUSB_TOP_P1_REF          199
#define CLK_TOP_SSUSB_PHY_P1_REF          200
#define CLK_TOP_SSUSB_TOP_P2_REF          201
#define CLK_TOP_SSUSB_PHY_P2_REF          202
#define CLK_TOP_SSUSB_TOP_P3_REF          203
#define CLK_TOP_SSUSB_PHY_P3_REF          204
#define CLK_TOP_NR_CLK                    205

/* INFRACFG_AO */
#define CLK_INFRA_AO_PMIC_TMR             0
#define CLK_INFRA_AO_PMIC_AP              1
#define CLK_INFRA_AO_PMIC_MD              2
#define CLK_INFRA_AO_PMIC_CONN            3
#define CLK_INFRA_AO_SEJ                  4
#define CLK_INFRA_AO_APXGPT               5
#define CLK_INFRA_AO_GCE                  6
#define CLK_INFRA_AO_GCE2                 7
#define CLK_INFRA_AO_THERM                8
#define CLK_INFRA_AO_PWM_HCLK             9
#define CLK_INFRA_AO_PWM1                 10
#define CLK_INFRA_AO_PWM2                 11
#define CLK_INFRA_AO_PWM3                 12
#define CLK_INFRA_AO_PWM4                 13
#define CLK_INFRA_AO_PWM                  14
#define CLK_INFRA_AO_UART0                15
#define CLK_INFRA_AO_UART1                16
#define CLK_INFRA_AO_UART2                17
#define CLK_INFRA_AO_UART3                18
#define CLK_INFRA_AO_UART4                19
#define CLK_INFRA_AO_GCE_26M              20
#define CLK_INFRA_AO_CQ_DMA_FPC           21
#define CLK_INFRA_AO_UART5                22
#define CLK_INFRA_AO_HDMI_26M             23
#define CLK_INFRA_AO_SPI0                 24
#define CLK_INFRA_AO_MSDC0                25
#define CLK_INFRA_AO_MSDC1                26
#define CLK_INFRA_AO_MSDC2                27
#define CLK_INFRA_AO_MSDC0_SRC            28
#define CLK_INFRA_AO_DVFSRC               29
#define CLK_INFRA_AO_TRNG                 30
#define CLK_INFRA_AO_AUXADC               31
#define CLK_INFRA_AO_CPUM                 32
#define CLK_INFRA_AO_HDMI_32K             33
#define CLK_INFRA_AO_CEC_66M_HCLK         34
#define CLK_INFRA_AO_PCIE_TL_26M          35
#define CLK_INFRA_AO_MSDC1_SRC            36
#define CLK_INFRA_AO_CEC_66M_BCLK         37
#define CLK_INFRA_AO_PCIE_TL_96M          38
#define CLK_INFRA_AO_DEVICE_APC           39
#define CLK_INFRA_AO_ECC_66M_HCLK         40
#define CLK_INFRA_AO_DEBUGSYS             41
#define CLK_INFRA_AO_AUDIO                42
#define CLK_INFRA_AO_PCIE_TL_32K          43
#define CLK_INFRA_AO_DBG_TRACE            44
#define CLK_INFRA_AO_DRAMC_F26M           45
#define CLK_INFRA_AO_IRTX                 46
#define CLK_INFRA_AO_DISP_PWM             47
#define CLK_INFRA_AO_CLDMA_BCLK           48
#define CLK_INFRA_AO_AUDIO_26M_BCLK       49
#define CLK_INFRA_AO_SPI1                 50
#define CLK_INFRA_AO_SPI2                 51
#define CLK_INFRA_AO_SPI3                 52
#define CLK_INFRA_AO_FSSPM                53
#define CLK_INFRA_AO_SSPM_BUS_HCLK        54
#define CLK_INFRA_AO_APDMA_BCLK           55
#define CLK_INFRA_AO_SPI4                 56
#define CLK_INFRA_AO_SPI5                 57
#define CLK_INFRA_AO_CQ_DMA               58
#define CLK_INFRA_AO_MSDC0_SELF           59
#define CLK_INFRA_AO_MSDC1_SELF           60
#define CLK_INFRA_AO_MSDC2_SELF           61
#define CLK_INFRA_AO_I2S_DMA              62
#define CLK_INFRA_AO_AP_MSDC0             63
#define CLK_INFRA_AO_MD_MSDC0             64
#define CLK_INFRA_AO_MSDC30_2             65
#define CLK_INFRA_AO_GCPU                 66
#define CLK_INFRA_AO_PCIE_PERI_26M        67
#define CLK_INFRA_AO_GCPU_66M_BCLK        68
#define CLK_INFRA_AO_GCPU_133M_BCLK       69
#define CLK_INFRA_AO_DISP_PWM1            70
#define CLK_INFRA_AO_FBIST2FPC            71
#define CLK_INFRA_AO_DEVICE_APC_SYNC      72
#define CLK_INFRA_AO_PCIE_P1_PERI_26M     73
#define CLK_INFRA_AO_133M_MCLK_CK         74
#define CLK_INFRA_AO_66M_MCLK_CK          75
#define CLK_INFRA_AO_PCIE_PL_P_250M_P0    76
#define CLK_INFRA_AO_RG_AES_MSDCFDE_CK_0P 77
#define CLK_INFRA_AO_NR_CLK               78

/* APMIXEDSYS */
#define CLK_APMIXED_ETHPLL          0
#define CLK_APMIXED_MSDCPLL         1
#define CLK_APMIXED_TVDPLL1         2
#define CLK_APMIXED_TVDPLL2         3
#define CLK_APMIXED_MMPLL           4
#define CLK_APMIXED_MAINPLL         5
#define CLK_APMIXED_IMGPLL          6
#define CLK_APMIXED_UNIVPLL         7
#define CLK_APMIXED_ADSPPLL         8
#define CLK_APMIXED_APLL1           9
#define CLK_APMIXED_APLL2           10
#define CLK_APMIXED_APLL3           11
#define CLK_APMIXED_APLL4           12
#define CLK_APMIXED_APLL5           13
#define CLK_APMIXED_MFGPLL          14
#define CLK_APMIXED_PLL_SSUSB26M_EN 15
#define CLK_APMIXED_NR_CLK          16

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MTK_MT8188_CLOCK_H_ */
